contact_links:
  - name: Ask questions
    url: https://github.com/giswqs/open-data/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Ideas
    url: https://github.com/giswqs/open-data/discussions/categories/ideas
    about: Please share your ideas here.
  - name: Ask questions from the geospatial community
    url: https://gis.stackexchange.com/questions/tagged/geospatial
    about: To get answers from questions in the geospatial community, please ask and answer questions here.
